name: ArchersBattle
version: 1.0
main: net.mcmhsj.archersbattle.Main
author: Soldier
commands:
  ab:
    description: Main command of ArchersBattle
  abadmin:
    description: Admin command Of ArchersBattle